[package]
name = "menace"
version = "0.1.0"
authors = ["dakatk <dakatk97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"